### ISSUE TITLE
Request for ipython tries to install old ipython

### ISSUE THREAD

**Issue by itziakos** [enthought/sat-solver#143]
Using jaguar/sat_solver and running `jaguar install ipython` jaguar is trying to install ipython-3.0.0-1 (which fails https://github.com/enthought/buildsystem/issues/567).

I would expect to get ipython 4.0.0-4

```
                  2.3.1-3    enthought/free
                  2.3.1-4    enthought/free
                  2.4.1-1    enthought/free
                  3.0.0-1    enthought/free
                  3.0.0-2    enthought/free
                  3.0.0-3    enthought/free
                  3.1.0-1    enthought/free
                  3.1.0-2    enthought/free
                  3.2.0-1    enthought/free
                  3.2.1-1    enthought/free
                  4.0.0-2    enthought/free
                  4.0.0-3    enthought/free
                  4.0.0-4  enthought/free
ipython4          4.0.0-2    enthought/free
                  4.0.0-3    enthought/free
                  4.0.0-4    enthought/free
                  4.0.0-5    enthought/free
                  4.0.0-6    enthought/free
```

**Comment by johntyree** [comment]
Is this in a clean environment?

**Comment by itziakos** [comment]
No I had installed traits, nose and haas from sources

**Comment by johntyree** [comment]
OK.

The default behavior of jaguar is currently to try to preserve versions
that you already have installed. I'll consider this a point in favor of not
doing that, or at least communicating it properly to the user.

If you run `jaguar --update-all` right now I expect it will give you the
versions that you want or tell you why it's not possible to have the latest
version of all of your packages. If you want to just update ipython and do
whatever is necessary for that to happen, you can try `jaguar update
ipython`.

I think we're still working out the user interaction around all this.

2016-03-03 2:48 GMT-06:00 Ioannis Tziakos <notifications@github.com>:

> No I had installed traits, nose and haas from sources
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enthought/sat-solver/issues/143#issuecomment-191657268>
> .
>



-- 
John Tyree
Scientific Software Developer
Enthought, Inc.
www.enthought.com

**Comment by itziakos** [comment]
I am getting this weird behaviour 


```python
PS C:\Users\itziakos\Projects\sectiondoc\docs> jaguar install sphinx
Fetching package repositories indices.. done
Traceback (most recent call last):
  File "c:\pythons\cpython35\Lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\pythons\cpython35\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\jaguar\.env-35\lib\site-packages\jaguar-0.5.0.dev262-py3.5.egg\jaguar\__main__.py", line 5, in <module>
    main()
  File "C:\jaguar\.env-35\lib\site-packages\jaguar-0.5.0.dev262-py3.5.egg\jaguar\cli\main.py", line 56, in main
    return jaguar_cli(auto_envvar_prefix="JAGUAR", prog_name="jaguar")
  File "C:\jaguar\.env-35\lib\site-packages\click-6.3-py3.5.egg\click\core.py",
line 716, in __call__
    return self.main(*args, **kwargs)
  File "C:\jaguar\.env-35\lib\site-packages\click-6.3-py3.5.egg\click\core.py",
line 696, in main
    rv = self.invoke(ctx)
  File "C:\jaguar\.env-35\lib\site-packages\jaguar-0.5.0.dev262-py3.5.egg\jaguar\cli\utils.py", line 76, in invoke
    self._propagate_if_debug(ctx)
  File "C:\jaguar\.env-35\lib\site-packages\jaguar-0.5.0.dev262-py3.5.egg\jaguar\cli\utils.py", line 30, in invoke
    return super(_ErrorHandlingMixin, self).invoke(ctx)
  File "C:\jaguar\.env-35\lib\site-packages\jaguar-0.5.0.dev262-py3.5.egg\jaguar\cli\click_custom.py", line 81, in invoke
    click.Group.invoke(self, ctx)
  File "C:\jaguar\.env-35\lib\site-packages\click-6.3-py3.5.egg\click\core.py",
line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\jaguar\.env-35\lib\site-packages\click-6.3-py3.5.egg\click\core.py",
line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\jaguar\.env-35\lib\site-packages\click-6.3-py3.5.egg\click\core.py",
line 534, in invoke
    return callback(*args, **kwargs)
  File "C:\jaguar\.env-35\lib\site-packages\click-6.3-py3.5.egg\click\decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "C:\jaguar\.env-35\lib\site-packages\jaguar-0.5.0.dev262-py3.5.egg\jaguar\cli\packages.py", line 77, in install_package
    implementation
  File "C:\jaguar\.env-35\lib\site-packages\jaguar-0.5.0.dev262-py3.5.egg\jaguar\commands\packages.py", line 49, in install_cmd
    return _install_requirements(session)
  File "C:\jaguar\.env-35\lib\site-packages\jaguar-0.5.0.dev262-py3.5.egg\jaguar\commands\packages.py", line 38, in _install_requirements
    return package_manager.install_command(requirement_strings)
  File "C:\jaguar\.env-35\lib\site-packages\jaguar-0.5.0.dev262-py3.5.egg\jaguar\core\packages_manager.py", line 215, in install_command
    self._repository, solver, request, manual_list)
  File "C:\jaguar\.env-35\lib\site-packages\jaguar-0.5.0.dev262-py3.5.egg\jaguar\core\packages_manager.py", line 602, in _actions_from_install_requirement
    actions, up_to_dates = solver.resolve(request, manual_list)
  File "C:\jaguar\.env-35\lib\site-packages\jaguar-0.5.0.dev262-py3.5.egg\jaguar\core\_sat_solver.py", line 97, in resolve
    transaction = self._solver.solve(request)
  File "C:\jaguar\.env-35\lib\site-packages\simplesat-0.2.0.dev1-py3.5.egg\simplesat\dependency_solver.py", line 36, in solve
    request
  File "C:\jaguar\.env-35\lib\site-packages\simplesat-0.2.0.dev1-py3.5.egg\simplesat\dependency_solver.py", line 90, in _create_rules_and_initialize_policy
    return all_requirement_ids, list(rules_generator.iter_rules())
  File "C:\jaguar\.env-35\lib\site-packages\simplesat-0.2.0.dev1-py3.5.egg\simplesat\rules_generator.py", line 151, in iter_rules
    self._add_installed_package_rules(package)
  File "C:\jaguar\.env-35\lib\site-packages\simplesat-0.2.0.dev1-py3.5.egg\simplesat\rules_generator.py", line 382, in _add_installed_package_rules
    self._add_package_rules(other)
  File "C:\jaguar\.env-35\lib\site-packages\simplesat-0.2.0.dev1-py3.5.egg\simplesat\rules_generator.py", line 335, in _add_package_rules
    self._add_install_requires_rules(p, work_queue)
  File "C:\jaguar\.env-35\lib\site-packages\simplesat-0.2.0.dev1-py3.5.egg\simplesat\rules_generator.py", line 280, in _add_install_requires_rules
    "dependency {1!r}".format(requirement.name, package))
AssertionError: No candidates found for requirement 'terminado', needed for dependency RepositoryPackageMetadata('ipython-3.0.0-1', repo=Repository(<enthought/free>))
PS C:\Users\itziakos\Projects\sectiondoc\docs>
```

I am not sure why sat solver tries to check the requirements of ipython-3.0.0-1 when I request sphinx.
Is this a jaguar error?

Please note that I have already installed ipython 4 (using enpkg with legacy solver)
```
                  2.4.1-1    enthought/free
                  3.0.0-1    enthought/free
                  3.0.0-2    enthought/free
                  3.0.0-3    enthought/free
                  3.1.0-1    enthought/free
                  3.1.0-2    enthought/free
                  3.2.0-1    enthought/free
                  3.2.1-1    enthought/free
                  4.0.0-2    enthought/free
                  4.0.0-3    enthought/free
                  * 4.0.0-4  enthought/free
                  4.0.0-5    enthought/free
ipython4          4.0.0-2    enthought/free
                  4.0.0-3    enthought/free
                  4.0.0-4    enthought/free
                  4.0.0-5    enthought/free
                  4.0.0-6    enthought/free
                  4.0.0-7    enthought/free
                  4.0.0-8    enthought/free
                  4.0.0-9    enthought/free
                  4.0.1-1    enthought/free
                  * 4.0.1-2  enthought/free
                  4.1.2-1    enthought/free
ipython_genutils  * 0.1.0-1  enthought/free
PS C:\Users\itziakos\Projects\sectiondoc\docs>
```

**Comment by johntyree** [comment]
It considers all versions of all currently installed packages in case it
needs to upgrade or downgrade to maintain compatibility. For example, your
version of ipython might conflict with something else we'd like to install.
In this case, we'll attempt to keep *some* version of ipython installed.
