### ISSUE TITLE
New release of attrs package (19.2.0) breaks simplesat.

### ISSUE THREAD

**Issue by benreynwar** [enthought/sat-solver#270]
The attrs package recently released a new version (19.2.0) which breaks simplesat.

```
Python 3.7.3 (default, Aug 20 2019, 17:04:43) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import simplesat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ben/.virtualenvs/deleteme/lib/python3.7/site-packages/simplesat/__init__.py", line 3, in <module>
    from .constraints import Requirement, InstallRequirement
  File "/home/ben/.virtualenvs/deleteme/lib/python3.7/site-packages/simplesat/constraints/__init__.py", line 5, in <module>
    from .constraint_modifiers import (
  File "/home/ben/.virtualenvs/deleteme/lib/python3.7/site-packages/simplesat/constraints/constraint_modifiers.py", line 85, in <module>
    class ConstraintModifiers(object):
  File "/home/ben/.virtualenvs/deleteme/lib/python3.7/site-packages/simplesat/constraints/constraint_modifiers.py", line 86, in ConstraintModifiers
    allow_newer = attr(**_coerced_set)
TypeError: attrib() got an unexpected keyword argument 'convert'
```

**Comment by itziakos** [comment]
fixed by #271

**Comment by xmentos** [comment]
Great and thanks for fixing. Can this be released because it breaks several other packages depending on simplesat (in my case https://github.com/olofk/fusesoc)?

**Comment by itziakos** [comment]
@xmentos  the updated simplesat version 0.8.2 has been uploaded to pypi
