### ISSUE TITLE
Crash with simple `>=` request

### ISSUE THREAD

**Issue by cournape** [enthought/sat-solver#42]
This scenario is failing:

```
packages:
  - libgfortran 3.0.0-1
  - libgfortran 3.0.0-2
  - MKL 10.2-1
  - MKL 10.2-2
  - MKL 10.3-1
  - numpy 1.5.1-1; depends (MKL == 10.3-1)
  - numpy 1.5.1-2; depends (MKL == 10.3-1)
  - numpy 1.6.0b2-1; depends (MKL == 10.3-1)
  - numpy 1.6.0-1; depends (MKL == 10.3-1)
  - numpy 1.6.0-2; depends (MKL == 10.3-1)
  - numpy 1.6.0-3; depends (MKL == 10.3-1)
  - numpy 1.6.0-4; depends (MKL == 10.3-1)
  - numpy 1.6.0-5; depends (MKL == 10.3-1)
  - numpy 1.6.1-1; depends (MKL == 10.3-1)
  - numpy 1.6.1-2; depends (MKL == 10.3-1)
  - numpy 1.6.1-3; depends (MKL == 10.3-1)
  - numpy 1.6.1-5; depends (MKL == 10.3-1)
  - numpy 1.7.1-1; depends (MKL == 10.3-1)
  - numpy 1.7.1-2; depends (MKL == 10.3-1)
  - numpy 1.7.1-3; depends (MKL == 10.3-1)
  - numpy 1.8.0-1; depends (MKL == 10.3-1)
  - numpy 1.8.0-2; depends (MKL == 10.3-1)
  - numpy 1.8.0-3; depends (MKL == 10.3-1)
  - numpy 1.8.1-1; depends (MKL == 10.3-1)
  - numpy 1.8.1-2; depends (MKL == 10.3-1)
  - numpy 1.8.1-3; depends (libgfortran ~= 3.0.0, MKL == 10.3-1)
  - numpy 1.9.2-1; depends (libgfortran ~= 3.0.0, MKL == 10.3-1)

request:
    - operation: "install"
      requirement: "numpy >= 1.9.2"
````

with the following traceback:

```
Traceback (most recent call last):
  File "scripts/pysolver_policy.py", line 35, in <module>
    main()
  File "scripts/pysolver_policy.py", line 31, in main
    scenario.installed_repository, ns.print_ids)
  File "scripts/pysolver_policy.py", line 16, in solve_and_print
    transaction = solver.solve(request)
  File "/home/davidc/src/enthought/sat-solver/simplesat/pysolver_with_policy.py", line 23, in solve
    solution = sat_solver.search()
  File "/home/davidc/src/enthought/sat-solver/simplesat/sat/minisat.py", line 141, in search
    self.clauses,
  File "/home/davidc/src/enthought/sat-solver/simplesat/sat/policy.py", line 64, in get_next_package_id
    "Trying to assign to a variable which is already assigned."
AssertionError: Trying to assign to a variable which is already assigned.
```

**Comment by johntyree** [comment]
:( mine also failed on this.

In my case, it had to do with propagating constraints a priori. The policy was assuming that the first time it sees a pkg_id, it will be unassigned.
